name: Build & Push (GHCR)
on:
  push:
    branches: [ main ]
permissions:
  contents: read
  packages: write
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set environment variables
        id: env
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.API_BASE_URL }}" >> $GITHUB_ENV
          echo "VITE_WS_URL=${{ secrets.WS_URL }}" >> $GITHUB_ENV
          

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            VITE_API_BASE_URL=${{ env.VITE_API_BASE_URL }}
            VITE_WS_URL=${{ env.VITE_WS_URL }}
          tags: |
            ghcr.io/quiby-ai/frontend:${{ github.sha }}
            ghcr.io/quiby-ai/frontend:main
          # optional: multiarch
          # platforms: linux/amd64,linux/arm64
